### PR TITLE
Sentry

### PR DESCRIPTION
**Pull request by vojta-janousek**

### CODE REVIEW

**Review by radekholy24 — COMMENTED** [review]
The Sentry integration looks good. I would have merged it if it was alone. Is the Prometheus integration finished already or is it still in progress?

**Comment by vojta-janousek** [comment]
> The Sentry integration looks good. I would have merged it if it was alone. Is the Prometheus integration finished already or is it still in progress?

I have no idea. There's definitely no scraping set up and the MetricsHandler doesn't work (I think it has to run in a separate container).

It has a counter that clicks up, and a metrics endpoint that shows the count, but that could've been done without Prometheus so I'm guessing it still needs some work.

**Comment by radekholy24** [comment]
OK, I was rather asking whether the PR is ready for a review and as I understand, it is. So, we can either move the Prometheus integration into another branch (since it still needs some tweaks) and merge this or we can finish the Prometheus work here...

As for the Prometheus, I still need to test the `/metrics` endpoint, but if it does what it should, we don't need the `core/metrics.py` file. But what I miss is the [labels](https://github.com/prometheus/client_python#labels). We need a `link_id` label that contains the ID of the link that is counted so that users can watch the stats per link. Also a [Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) label might be interesting but consider it optional.

**Comment by radekholy24** [comment]
Cool, looks good to me. I just realized one more thing. Since our deployment always deploys `master`, merging this would break it. Could you please make a PR that adds `SENTRY_DSN` to `settings.ini` in our deployment repo?

**Comment by vojta-janousek** [comment]
SENTRY_DSN added to settings.ini on GitLab.

**Pull request merged**
